apiVersion: v1

data:

  tls.crt: "<<---base64 encoded ssl cert--->>"

  tls.key: "<<---base64 encoded cert key--->>"

kind: Secret

metadata:

  name: api-tls-secret

  namespace: default

type: Opaque
